# Generated by Django 5.0.3 on 2024-06-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id_blog', models.SlugField(max_length=255, primary_key=True, serialize=False)),
                ('kategori', models.CharField(max_length=50)),
                ('tanggal', models.DateField()),
                ('penulis', models.CharField(max_length=100)),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('gambar', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Buku',
            fields=[
                ('id_buku', models.SlugField(max_length=255, primary_key=True, serialize=False)),
                ('gambar', models.ImageField(upload_to='')),
                ('judul', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('penerbit', models.CharField(max_length=100)),
                ('penulis', models.CharField(max_length=100)),
                ('editor', models.CharField(max_length=100)),
                ('ukuran', models.CharField(max_length=50)),
                ('halaman', models.IntegerField()),
                ('sinopsis', models.TextField()),
                ('harga', models.IntegerField()),
                ('link', models.URLField()),
                ('stok', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PeralatanPendidikan',
            fields=[
                ('id_peralatan_pendidikan', models.SlugField(max_length=255, primary_key=True, serialize=False)),
                ('gambar', models.ImageField(upload_to='')),
                ('nama_peralatan', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=50)),
                ('kategori', models.CharField(max_length=50)),
                ('deskripsi', models.TextField()),
                ('harga', models.IntegerField()),
                ('link', models.URLField()),
                ('stok', models.IntegerField()),
            ],
        ),
    ]
